### ISSUE TITLE
entity 작성

### ISSUE THREAD

**Issue by yejin0718** [Challenge02/Challenge02-BE#1]
# Description
entity 작성

## Todo
- [ ] Music enitty 작성
- [ ] Artist enitty 작성
- [ ] Memebr enitty 작성
- [ ] play_history enitty 작성
- [ ] genre enitty 작성

## Etc
기타사항을 작성해주세요.
